version: '3'
services:
    conda:
        build: .
        ports:
            - "8888:8888"
            - "6006:6006"
        volumes:
            - ../pyimagesearch-pytorch:/usr/src/app
        working_dir: /usr/src/app
        environment:
            - DISPLAY=host.docker.internal:0
        command: /bin/bash -c "jupyter-lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root"